### ISSUE TITLE
[Bug] something wrong with settings in chat importing a json in prompt template

### ISSUE THREAD

**Issue by johnfelipe** [Yidadaa/ChatGPT-Next-Web#2409] opened 2023-07-16 11:24 UTC
<code>
		at am (https://chat-gpt-next-web-1-5svxd3xjy-johnfelipe.vercel.app/_next/static/chunks/bce60fc1-f224b59aead20a45.js:9:68612)
		at am (https://chat-gpt-next-web-1-5svxd3xjy-johnfelipe.vercel.app/_next/static/chunks/bce60fc1-f224b59aead20a45.js:9:68612)
		at div
		at D (https://chat-gpt-next-web-1-5svxd3xjy-johnfelipe.vercel.app/_next/static/chunks/4294.ceff0fdfa187b632.js:1:20337)
		at am (https://chat-gpt-next-web-1-5svxd3xjy-johnfelipe.vercel.app/_next/static/chunks/bce60fc1-f224b59aead20a45.js:9:68612)
		at div
		at div
		at am (https://chat-gpt-next-web-1-5svxd3xjy-johnfelipe.vercel.app/_next/static/chunks/bce60fc1-f224b59aead20a45.js:9:68612)
		at div
		at e4 (https://chat-gpt-next-web-1-5svxd3xjy-johnfelipe.vercel.app/_next/static/chunks/9626.8081bd03fd347bc9.js:1:37172)
		at div
		at e7 (https://chat-gpt-next-web-1-5svxd3xjy-johnfelipe.vercel.app/_next/static/chunks/9626.8081bd03fd347bc9.js:1:38139)
		at div
		at div
		at tt (https://chat-gpt-next-web-1-5svxd3xjy-johnfelipe.vercel.app/_next/static/chunks/9626.8081bd03fd347bc9.js:1:42332)
		at Suspense
		at LoadableComponent
		at P (https://chat-gpt-next-web-1-5svxd3xjy-johnfelipe.vercel.app/_next/static/chunks/3392-9f4f96efd8aa7577.js:36:3268)
		at T (https://chat-gpt-next-web-1-5svxd3xjy-johnfelipe.vercel.app/_next/static/chunks/3392-9f4f96efd8aa7577.js:36:4265)
		at div
		at div
		at Q (https://chat-gpt-next-web-1-5svxd3xjy-johnfelipe.vercel.app/_next/static/chunks/app/page-75df3b962dd64286.js:1:37483)
		at _ (https://chat-gpt-next-web-1-5svxd3xjy-johnfelipe.vercel.app/_next/static/chunks/3392-9f4f96efd8aa7577.js:36:3683)
		at v (https://chat-gpt-next-web-1-5svxd3xjy-johnfelipe.vercel.app/_next/static/chunks/3392-9f4f96efd8aa7577.js:27:627)
		at am (https://chat-gpt-next-web-1-5svxd3xjy-johnfelipe.vercel.app/_next/static/chunks/bce60fc1-f224b59aead20a45.js:9:68612)
		at et (https://chat-gpt-next-web-1-5svxd3xjy-johnfelipe.vercel.app/_next/static/chunks/app/page-75df3b962dd64286.js:1:38444)
		at O (https://chat-gpt-next-web-1-5svxd3xjy-johnfelipe.vercel.app/_next/static/chunks/7698-b373887463486dae.js:1:18966)
		at am (https://chat-gpt-next-web-1-5svxd3xjy-johnfelipe.vercel.app/_next/static/chunks/bce60fc1-f224b59aead20a45.js:9:68612)
		at c (https://chat-gpt-next-web-1-5svxd3xjy-johnfelipe.vercel.app/_next/static/chunks/7698-b373887463486dae.js:1:28611)
		at a (https://chat-gpt-next-web-1-5svxd3xjy-johnfelipe.vercel.app/_next/static/chunks/7698-b373887463486dae.js:1:26598)
		at P (https://chat-gpt-next-web-1-5svxd3xjy-johnfelipe.vercel.app/_next/static/chunks/7698-b373887463486dae.js:1:20547)
		at c (https://chat-gpt-next-web-1-5svxd3xjy-johnfelipe.vercel.app/_next/static/chunks/7698-b373887463486dae.js:1:15257)
		at am (https://chat-gpt-next-web-1-5svxd3xjy-johnfelipe.vercel.app/_next/static/chunks/bce60fc1-f224b59aead20a45.js:9:68612)
		at g (https://chat-gpt-next-web-1-5svxd3xjy-johnfelipe.vercel.app/_next/static/chunks/7698-b373887463486dae.js:1:18712)
		at am (https://chat-gpt-next-web-1-5svxd3xjy-johnfelipe.vercel.app/_next/static/chunks/bce60fc1-f224b59aead20a45.js:9:68612)
		at E (https://chat-gpt-next-web-1-5svxd3xjy-johnfelipe.vercel.app/_next/static/chunks/7698-b373887463486dae.js:1:20789)
		at body
		at html
		at am (https://chat-gpt-next-web-1-5svxd3xjy-johnfelipe.vercel.app/_next/static/chunks/bce60fc1-f224b59aead20a45.js:9:68612)
		at c (https://chat-gpt-next-web-1-5svxd3xjy-johnfelipe.vercel.app/_next/static/chunks/7698-b373887463486dae.js:1:28611)
		at am (https://chat-gpt-next-web-1-5svxd3xjy-johnfelipe.vercel.app/_next/static/chunks/bce60fc1-f224b59aead20a45.js:9:68612)
		at a (https://chat-gpt-next-web-1-5svxd3xjy-johnfelipe.vercel.app/_next/static/chunks/7698-b373887463486dae.js:1:26598)
		at M (https://chat-gpt-next-web-1-5svxd3xjy-johnfelipe.vercel.app/_next/static/chunks/7698-b373887463486dae.js:1:9225)
		at am (https://chat-gpt-next-web-1-5svxd3xjy-johnfelipe.vercel.app/_next/static/chunks/bce60fc1-f224b59aead20a45.js:9:68612)
		at c (https://chat-gpt-next-web-1-5svxd3xjy-johnfelipe.vercel.app/_next/static/chunks/7698-b373887463486dae.js:1:15257)
		at w (https://chat-gpt-next-web-1-5svxd3xjy-johnfelipe.vercel.app/_next/static/chunks/7698-b373887463486dae.js:1:12734)
		at w (https://chat-gpt-next-web-1-5svxd3xjy-johnfelipe.vercel.app/_next/static/chunks/7698-b373887463486dae.js:1:4264)
		at A
		at x (https://chat-gpt-next-web-1-5svxd3xjy-johnfelipe.vercel.app/_next/static/chunks/7698-b373887463486dae.js:1:4636)</code>

pls view video

https://github.com/Yidadaa/ChatGPT-Next-Web/assets/428820/41930e85-17f0-4e75-98e8-191c17252cc2

**Comment by Yidadaa** [comment] 2023-07-16 15:03
Does this error occur every time you click the button?

**Comment by johnfelipe** [comment] 2023-07-16 15:23
when clear all data all my 38 prompts dissapear

download 
chatgpt-next-web-snapshot.json

and nothing happend

**Comment by Yidadaa** [comment] 2023-07-16 15:38
Sorry to hear about that, clearing all data is dangerous. This error is caused by loading a old version bundle from server, if your code was re-deployed, and once you clicked the setting button, it would try to load a old version file, and get nothing from server, and then this error occurs.

All you need to do is to refresh the page, but not clear the data. This dangerous button is placed for unrecoverable errors, which can not be fixed by reloading page.

**Comment by johnfelipe** [comment] 2023-07-16 16:34
https://drive.google.com/file/d/1GG72u--MwFHL5HQHBEBFykvCuxvHMFQb/view?usp=sharing

is not working refresh page, pls view video

**Comment by Yidadaa** [comment] 2023-07-17 02:52
I understand, thank you, this is a bug, would you please attach the json file in the video here?

**Comment by Yidadaa** [comment] 2023-07-17 03:04
fixed at #2412 , i have test it on my computer.

**Closed** 2023-07-17 03:03 UTC
Labels: bug

**Comment by johnfelipe** [comment] 2023-07-17 03:36
How can share Json file private?

**Comment by Yidadaa** [comment] 2023-07-17 06:41
Just fixed it, sync your code and check if it is solved.
